# Generated by Django 2.2 on 2020-02-16 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_auto_20190421_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['create_time'], 'verbose_name': '课程', 'verbose_name_plural': '课程'},
        ),
    ]
